-- =====================================================================
-- 001: 논문별 저자 관리 스키마
-- Supabase 대시보드 > SQL Editor 에서 한 번 실행하세요. (여러 번 실행해도 안전)
-- =====================================================================

-- 1) 저자 마스터(authors): 수정 시각 컬럼 추가
alter table public.authors add column if not exists updated_at timestamptz default now();

-- 2) 논문
create table if not exists public.papers (
  id          bigint generated by default as identity primary key,
  title       text not null,
  note        text,
  created_at  timestamptz not null default now()
);

-- 3) 논문-저자 연결 (소속·서명은 논문별 스냅샷)
create table if not exists public.paper_authors (
  id                bigint generated by default as identity primary key,
  paper_id          bigint not null references public.papers(id)  on delete cascade,
  author_id         bigint not null references public.authors(id) on delete restrict,  -- 논문에 연결된 저자는 삭제 불가
  author_order      int     not null default 0,
  is_corresponding  boolean not null default false,
  affiliation_kr    text,
  affiliation_en    text,
  signature_url     text,
  signed_at         timestamptz,
  created_at        timestamptz not null default now(),
  unique (paper_id, author_id)
);
create index if not exists paper_authors_paper_idx  on public.paper_authors(paper_id);
create index if not exists paper_authors_author_idx on public.paper_authors(author_id);

-- 4) 권한: 비밀번호 없이 누구나 조회/추가/수정/삭제 (anon 키)
alter table public.authors       enable row level security;
alter table public.papers        enable row level security;
alter table public.paper_authors enable row level security;

drop policy if exists "public all" on public.authors;
drop policy if exists "public all" on public.papers;
drop policy if exists "public all" on public.paper_authors;
create policy "public all" on public.authors       for all to anon, authenticated using (true) with check (true);
create policy "public all" on public.papers        for all to anon, authenticated using (true) with check (true);
create policy "public all" on public.paper_authors for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.authors, public.papers, public.paper_authors to anon, authenticated;

-- 5) 기존 데이터 이전: 테스트 행 삭제 + 기존 저자들을 만성기침 논문 1편으로 묶기
delete from public.authors where id = 22 and name_en = 'TEST Author';

do $$
declare pid bigint;
begin
  if not exists (select 1 from public.papers) then
    insert into public.papers (title)
    values ('Real-World Patterns of Korean Medicine and Combined Korean–Western Medicine Use in Patients with Chronic Cough: A Nationwide Cohort Study')
    returning id into pid;

    -- 저자 순서는 기존 제출 순서(id 순)로 넣음 → 화면에서 실제 순서로 조정하세요
    insert into public.paper_authors (paper_id, author_id, author_order, affiliation_kr, affiliation_en, signature_url, signed_at)
    select pid, a.id, row_number() over (order by a.id), a.affiliation_kr, a.affiliation_en, a.signature_url,
           case when a.signature_url is not null then a.created_at end
    from public.authors a
    order by a.id;
  end if;
end $$;
